### ISSUE TITLE
InstallHook env variables checks are done in config files that should be ignored

### ISSUE THREAD

**Issue by tatyango** [Netcentric/system-env-install-hook#11]
Tool interprets variables in ACtool files https://github.com/Netcentric/accesscontroltool as InstallHook env variables. Even though these config files should not be checked for InstallHook env variables, cause:
- they are not explicitly listed to be adjusted
- they don't end with `.TEMPLATE`

Which causes a Failure during package instalation that CQ Env variables has not been set.
```ApplyEnvVarsInstallHook is active in netcentric:ubs-cp-platform-config-package:1.0.0-SNAPSHOT 
ApplyEnvVarsInstallHook checking if all env vars are set due to package property failForMissingEnvVar=true 
Env Variable 'namespace_name' is not found but ${ugc.name} is used in file //jcr_root/apps/<part-of-path-is-removed-intentionally>/platform/acls/author/administration-fragments.yaml without declaring a default 
Aborting installation of package <removed-intentionally>:<removed-intentionally>-platform-config-package:1.0.0-SNAPSHOT due to missing env variables```

**Comment by ghenzler** [comment]
Fixed in [v1.2.1](https://github.com/Netcentric/system-env-install-hook/releases/tag/1.2.1)
